package com.beppe.dao.DB1;

import com.beppe.entity.DB1.ExchangeOrder;
import com.beppe.entity.DB1.ExchangeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExchangeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int countByExample(ExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int deleteByExample(ExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int insert(ExchangeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    List<ExchangeOrder> selectByExample(ExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    ExchangeOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExchangeOrder record, @Param("example") ExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExchangeOrder record, @Param("example") ExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeOrder record);
}