spring:
    datasource:
        name: world
        url: jdbc:mysql://localhost:3306/goods_mall
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20




    redis:
        host: localhost
        port: 6379
        database: 5
        timeout: 10000

mybatis:
    type-aliases-package: com.dubbo.entity
    mapper-locations: classpath:com/dubbo/mapper/*.xml





logging:
#    file: log.log
    level:
        root: info
        com.dubbo.dao: CONSOLE
        com.dubbo.mappper: CONSOLE
        com.dubbo.serviceImpl: INFO
        com.dubbo.iservice: error




